import { useState } from 'react'
import jsPDF from 'jspdf'

const TempPasswordModal = ({ isOpen, email, password, onClose, facilityName }) => {
    const [copied, setCopied] = useState(false)

    if (!isOpen) return null

    const copy = async () => {
        try {
            await navigator.clipboard.writeText(password)
            setCopied(true)
            setTimeout(() => setCopied(false), 2000)
        } catch (_) {
            // ignore
        }
    }

    const downloadPDF = () => {
        try {
            const doc = new jsPDF()
            const now = new Date().toLocaleString()
            
            // Set up fonts and colors
            doc.setFont('helvetica')
            
            // Header with branding
            doc.setFontSize(24)
            doc.setTextColor(37, 99, 235) // Blue color for AidPoint
            doc.text('AidPoint', 20, 25)
            
            doc.setFontSize(20)
            doc.setTextColor(0, 0, 0)
            doc.text('Temporary Access Slip', 20, 40)
            
            doc.setFontSize(12)
            doc.setTextColor(100, 100, 100)
            doc.text(`${facilityName ? facilityName + ' • ' : ''}${now}`, 20, 50)
            
            // Add a line separator
            doc.setDrawColor(200, 200, 200)
            doc.line(20, 60, 190, 60)
            
            // Email section
            doc.setFontSize(10)
            doc.setTextColor(100, 116, 139)
            doc.text('EMAIL', 20, 80)
            
            doc.setFontSize(12)
            doc.setTextColor(0, 0, 0)
            doc.setFont('courier')
            // Add background rectangle for field
            doc.setFillColor(248, 250, 252)
            doc.rect(20, 85, 150, 12, 'F')
            doc.text(email, 25, 93)
            
            // Password section
            doc.setFont('helvetica')
            doc.setFontSize(10)
            doc.setTextColor(100, 116, 139)
            doc.text('TEMPORARY PASSWORD', 20, 115)
            
            doc.setFontSize(14)
            doc.setTextColor(0, 0, 0)
            doc.setFont('courier', 'bold')
            // Add background rectangle for field
            doc.setFillColor(248, 250, 252)
            doc.rect(20, 120, 150, 15, 'F')
            doc.text(password, 25, 130)
            
            // Warning section
            doc.setFont('helvetica')
            doc.setFillColor(254, 252, 232) // Light yellow background
            doc.setDrawColor(254, 240, 138) // Yellow border
            doc.rect(20, 150, 150, 25, 'FD')
            
            doc.setFontSize(10)
            doc.setTextColor(133, 77, 14)
            const warningText = 'This password is temporary. The staff member must verify their\nemail and change this password at first login.'
            doc.text(warningText, 25, 160)
            
            // Footer
            doc.setDrawColor(200, 200, 200)
            doc.line(20, 190, 190, 190)
            
            doc.setFontSize(9)
            doc.setTextColor(100, 116, 139)
            doc.text('Generated by Facility Portal', 20, 200)
            doc.text('Do not share insecurely', 130, 200)
            
            // Generate filename and download
            const filename = `temp-password-${email.replace('@', '-at-')}-${Date.now()}.pdf`
            doc.save(filename)
        } catch (error) {
            console.error('Error generating PDF:', error)
            // Fallback: show error message
            alert('Error generating PDF. Please try again.')
        }
    }

    return (
        <div className="fixed inset-0 z-50">
            <div className="absolute inset-0 bg-black/40" onClick={onClose} />
            <div className="relative z-10 mx-auto mt-24 w-full max-w-lg px-4">
                <div className="bg-white rounded-xl shadow-xl ring-1 ring-gray-200 overflow-hidden">
                    <div className="px-6 py-4 border-b border-gray-100 flex items-center justify-between">
                        <h3 className="text-lg font-semibold text-gray-900">Temporary Password Created</h3>
                        <button
                            onClick={onClose}
                            className="p-1.5 rounded hover:bg-gray-100 text-gray-500"
                            aria-label="Close">
                            <svg className="h-5 w-5" viewBox="0 0 24 24" fill="none" stroke="currentColor"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M6 18L18 6M6 6l12 12"/></svg>
                        </button>
                    </div>

                    <div className="px-6 py-5 space-y-4">
                        <p className="text-sm text-gray-700">
                            Share this temporary password with <span className="font-medium text-gray-900">{email}</span> securely. They will be asked to verify their email and change this password after their first login.
                        </p>

                        <label className="block text-xs font-medium text-gray-600">Temporary password</label>
                        <div className="flex items-stretch gap-2">
                            <input
                                readOnly
                                value={password}
                                className="flex-1 border rounded-md px-3 py-2 font-mono text-sm bg-gray-50 text-gray-900"
                            />
                            <button
                                onClick={copy}
                                className="px-3 py-2 rounded-md bg-blue-600 text-white text-sm font-medium hover:bg-blue-700">
                                {copied ? 'Copied' : 'Copy'}
                            </button>
                        </div>

                        <div className="text-xs text-yellow-700 bg-yellow-50 border border-yellow-200 rounded-md p-3">
                            Never send passwords over insecure channels. Prefer in-person or an encrypted message.
                        </div>
                    </div>

                    <div className="px-6 py-4 bg-gray-50 border-t border-gray-100 flex items-center justify-between">
                        <button
                            onClick={downloadPDF}
                            className="inline-flex items-center justify-center rounded-md border border-blue-200 text-blue-700 hover:bg-blue-50 text-sm font-medium px-4 py-2">
                            <svg className="h-4 w-4 mr-2" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                                <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M12 10v6m0 0l-3-3m3 3l3-3m2 8H7a2 2 0 01-2-2V5a2 2 0 012-2h5.586a1 1 0 01.707.293l5.414 5.414a1 1 0 01.293.707V19a2 2 0 01-2 2z" />
                            </svg>
                            Download PDF
                        </button>
                        <button
                            onClick={onClose}
                            className="inline-flex items-center justify-center rounded-md bg-blue-600 hover:bg-blue-700 text-white text-sm font-medium px-4 py-2">
                            Done
                        </button>
                    </div>
                </div>
            </div>
        </div>
    )
}

export default TempPasswordModal
